# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'Female', b'FEMALE'), (b'Male', b'MALE')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pin_code', models.CharField(blank=True, max_length=120, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
